# Generated by Django 4.2.2 on 2023-06-27 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('image', models.URLField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.ManyToManyField(related_name='cart_items', to='website.product')),
                ('favorites', models.ManyToManyField(related_name='favorites', to='website.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermenu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
