# Generated by Django 4.2.2 on 2023-06-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='order_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='product_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
