# Generated by Django 4.2.2 on 2023-06-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_example_order_total_alter_example_product_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
